apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis
  namespace: demo
spec:
  serviceName: "redis-service"
  replicas: 2
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:6.2.8-alpine
        ports:
        - containerPort: 6379
          name: master
        volumeMounts:
        - name: data
          mountPath: /var/lib/redis
      volumes:
        - name: config
          configMap:
            name: redis-ss-configuration
            items:
            - key: master.conf
              path: redis.conf

  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: storageclassredis
      resources:
        requests:
          storage: 500Mi
