kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: storageclassredis
  namespace: demo
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  fsType: ext3
volumeBindingMode: WaitForFirstConsumer
